# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "^.tox*|^fabfile*|^schedulesy/settings*"
fail_fast: true
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.4.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "2.2" ]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 21.11b0
    hooks:
    - id: black
  - repo: https://github.com/python-poetry/poetry
    rev: 1.2.0b2
    hooks:
      - id: poetry-check
      - id: poetry-lock
#      - id: poetry-export
#        args: ["-f", "requirements.txt", "-o", "requirements/auto-common.txt", "--without-hashes"]
  - repo: local
    hooks:
      - id: export-common-requirements
        name: Export requirements/auto-prod.txt
        language: system
        pass_filenames: false
        entry: poetry export --without-hashes -o requirements/auto-common.txt
        files: ^(pyproject.toml|poetry.lock)$
  - repo: local
    hooks:
      - id: export-dev-requirements
        name: Export requirements/auto-dev.txt
        language: system
        pass_filenames: false
        entry: poetry export --without-hashes -o requirements/auto-dev.txt --with dev
        files: ^(pyproject.toml|poetry.lock)$
