# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "^.tox*"
fail_fast: true
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.3.2
    hooks:
      - id: django-upgrade
        args: [--target-version, "2.2" ]
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
