# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "^.tox*|^fabfile*|^schedulesy/settings*"
fail_fast: true
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.13.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "3.2"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
  # - repo: https://github.com/python-poetry/poetry
  #   rev: 1.4.0
  #   hooks:
  #     - id: poetry-check
  #       args: [-vvv]
  #     - id: poetry-lock
  - repo: https://git.unistra.fr/community/poem
    rev: 1.0.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: [--only=develop]
      - id: export-common-requirements
      - id: export-dev-requirements
      - id: export-test-requirements
      - id: export-preprod-requirements
      - id: export-prod-requirements
