[tool.black]
line-length = 88
skip-string-normalization = true
target-version = ['py37']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | schedulesy\/settings
    | schedulesy\/apps\/ade_api\/migrations
    | schedulesy\/apps\/refresh\/migrations
    | fabfile
    | _build
    | buck-out
    | build
    | dist
  )/
  | manage.py
  | tox.ini
  | .coveragerc
                     # the root of the project
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.poetry]
name = "poetry-demo"
version = "0.1.0"
description = ""
authors = ["Virgile Gerecke <virgile.gerecke@unistra.fr>"]

[tool.poetry.dependencies]
python = "3.8"
Django = "~2.2.22"
djangorestframework-simplejwt = "4.6.0"
django-cors-headers = "3.7.0"
sentry-sdk = "~0.11"
django-cas-sso = "1.1.8"
celery = "5.2.2"
django-storages = "~1.7"
django-cacheops = "~4.2.0"
requests = "^2.28.0"
pytz = "2019.2"
britney-utils = "^0.1.2"
britney = "^0.5.1"
celery-skinos = "~0.2.0"
ua-parser = "0.8.0"
python-logstash-async = "2.5.0"
cryptography = "^37.0.2"
django-health-check = "3.16.4"
ics = "~0.6.0"
TatSu = "~5.6.0"
elasticsearch = "~7.1.0"
psycopg2 = "~2.8.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
coverage = "^6.4.1"
Sphinx = "^5.0.1"
pylint = "^2.14.1"
pycodestyle = "^2.8.0"
django-debug-toolbar = "~2.2.0"
django-extensions = "^3.1.5"
tox = "^3.25.0"
safety = "^1.10.3"
black = "^22.3.0"
pipdeptree = "^2.2.1"
pre-commit = "^2.19.0"
tox-poetry = "^0.4.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
