# Generated by Django 2.2.4 on 2019-08-23 13:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=25)),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
