# Generated by Django 2.2.4 on 2019-08-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulesy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='ext_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
