# Generated by Django 2.2.4 on 2019-08-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulesy', '0002_auto_20190823_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='ext_id',
            field=models.CharField(db_index=True, max_length=25, unique=True),
        ),
    ]
