# Generated by Django 2.2.4 on 2019-08-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulesy', '0003_auto_20190823_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=25)),
                ('method', models.CharField(max_length=50)),
                ('fingerprint', models.CharField(max_length=50)),
            ],
        ),
    ]
