# Generated by Django 2.2.4 on 2019-08-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulesy', '0004_fingerprint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fingerprint',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
