# Generated by Django 2.1.11 on 2019-08-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('display_configuration', models.CharField(blank=True, db_column='configuration_affichage', max_length=60)),
                ('resources', models.CharField(blank=True, db_column='ressources', max_length=300)),
                ('directory_id', models.CharField(db_column='uds_directory_id', max_length=32)),
                ('rh_id', models.CharField(blank=True, db_column='code_harp', max_length=15)),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='date_creation', null=True)),
                ('customization_date', models.DateTimeField(auto_now=True, db_column='date_personnalisation', null=True)),
                ('username', models.CharField(blank=True, db_column='uid', max_length=32)),
            ],
            options={
                'db_table': 'w_edtperso',
                'managed': False,
            },
        ),
    ]
