# Generated by Django 2.1.11 on 2019-09-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ade_legacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customization',
            options={'managed': False, 'verbose_name': 'Customization', 'verbose_name_plural': 'Customizations'},
        ),
    ]
