# Generated by Django 2.2.4 on 2019-08-26 08:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=25)),
                ('method', models.CharField(max_length=50)),
                ('fingerprint', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(db_index=True, max_length=25, unique=True)),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
