# Generated by Django 2.1.11 on 2019-09-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ade_api', '0002_displaytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ade_url', models.URLField(verbose_name='ADE URL')),
                ('project_id', models.IntegerField(help_text='projectId parameter', verbose_name='Project ID')),
                ('calendar_type', models.CharField(default='ical', help_text='calType parameter', max_length=50, verbose_name='Calendar type')),
                ('weeks_number', models.IntegerField(help_text='nbWeeks paramater', verbose_name='Weeks number')),
            ],
            options={'verbose_name': 'ADE config', 'verbose_name_plural': 'ADE config'},
        ),
        migrations.AlterModelOptions(
            name='fingerprint',
            options={'verbose_name': 'Fingerprint', 'verbose_name_plural': 'Fingerprints'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
    ]
