# Generated by Django 2.1.12 on 2019-09-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ade_api', '0003_auto_20190906_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCustomization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization_id', models.IntegerField(db_column='customization_id', unique=True)),
                ('directory_id', models.CharField(db_column='uds_directory_id', max_length=32)),
                ('username', models.CharField(blank=True, db_column='uid', max_length=32)),
                ('resources', models.ManyToManyField(to='ade_api.Resource')),
            ],
            options={
                'verbose_name': 'Local Customization',
                'verbose_name_plural': 'Local Customizations',
            },
        ),
    ]
