# Generated by Django 2.1.11 on 2019-09-26 13:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ade_api', '0005_auto_20190924_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
