# Generated by Django 2.1.12 on 2019-09-26 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ade_api', '0005_auto_20190924_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ade_api.Resource'),
        ),
    ]
