# Generated by Django 2.1.12 on 2019-09-26 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ade_api', '0006_auto_20190926_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ade_api.Resource'),
        ),
    ]
