# Generated by Django 2.1.11 on 2019-09-30 06:16

from django.db import migrations, models
import django.db.models.deletion
import schedulesy.apps.ade_api.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ade_api', '0007_resource_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=schedulesy.apps.ade_api.utils.generate_uuid, max_length=36, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Access',
                'verbose_name_plural': 'Accesses'
            },
        ),
        migrations.AlterField(
            model_name='localcustomization',
            name='customization_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='access',
            name='customization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='ade_api.LocalCustomization'),
        ),
        migrations.AlterUniqueTogether(
            name='access',
            unique_together={('name', 'customization')},
        ),
    ]
