# Generated by Django 2.1.12 on 2019-09-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ade_api', '0008_auto_20190927_2146'),
        ('ade_api', '0008_auto_20190930_0816'),
    ]

    operations = [
    ]
