# Generated by Django 2.1.12 on 2019-10-04 12:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ade_api', '0009_merge_20190930_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcustomization',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
