# Generated by Django 3.2.15 on 2022-08-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ade_api', '0011_resource_events_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeconfig',
            name='parameters',
            field=models.JSONField(verbose_name='Parameters'),
        ),
        migrations.AlterField(
            model_name='localcustomization',
            name='configuration',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='events',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
